name: CI/CD

on:
  # pull_request:
  #   branches: [ main ]
  # push:
  #   branches: [ main ]
  #   tags:
  #     - 'deploy-dev*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-test-solution:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build & Test .NET Application
      run: make dotnet-build dotnet-test
    - name: Login to Azure
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: ACR build
      run: make proj-acr-build
    - name: Get AKS Credentials
      run: make aks-get-credentials
    - name: Deploy to AKS
      run: make k8s-deploy
